# Configs for Weight Sharing ConvMixer
TRAIN:
  ENABLE: True
  DATASET: imagenet
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  MIXED_PRECISION: True
DATA:
  PATH_TO_DATA_DIR:
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  NUM_FRAMES: 1
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333333333333333]
CONVMIXER:
  CHANNEL: 768
  PATCH_KERNEL: 14
  PATCH_STRIDE: 14
  PATCH_PADDING: 0
  KERNEL: 3
  DEPTH: 32
  ACT_FUNC: RELU
  WEIGHT_SHARE:
    ENABLE: True
    SHARING_DISTRIBUTION: uniform
    SHARING_MAPPING: sequential
    SHARE_RATE: 2
AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m9-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.5
  CUTMIX_ALPHA: 0.5
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  BASE_LR: 0.01
  BASE_LR_SCALE_NUM_SHARDS: False
  LR_POLICY: onecycle
  MAX_EPOCH: 300
  OPTIMIZING_METHOD: adamw
  WEIGHT_DECAY: 2e-5
  MOMENTUM: 0.9
  WARMUP_EPOCHS: 0.0
  CLIP_GRAD_L2NORM: 1.0
MODEL:
  NUM_CLASSES: 1000
  ARCH: 2d
  MODEL_NAME: WSConvMixer
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: imagenet
  BATCH_SIZE: 256
  CHECKPOINT_FILE_PATH: 
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./
